    warning_form=QtGui.QWidget()
    warning_form.setWindowFlags(QtCore.Qt.Dialog)
    warning_form.setObjectName(_fromUtf8("warning_form"))
    warning_form.setWindowModality(QtCore.Qt.ApplicationModal)
    warning_form.resize(341, 105)
    warning_form.setWindowOpacity(0.98)
    warning_form.ok_button = QtGui.QDialogButtonBox(warning_form)
    warning_form.ok_button.setGeometry(QtCore.QRect(80, 70, 156, 23))
    warning_form.ok_button.setStandardButtons(QtGui.QDialogButtonBox.Ok)
    warning_form.ok_button.setObjectName(_fromUtf8("ok_button"))
    warning_form.imagen = QtGui.QLabel(warning_form)
    warning_form.imagen.setGeometry(QtCore.QRect(10, 10, 101, 91))
    warning_form.imagen.setText(_fromUtf8(""))
    warning_form.imagen.setPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/recursos/errorIco.png")))
    warning_form.imagen.setObjectName(_fromUtf8("imagen"))
    warning_form.mensaje = QtGui.QLabel(warning_form)
    warning_form.mensaje.setGeometry(QtCore.QRect(70, 20, 261, 20))
    font = QtGui.QFont()
    font.setPointSize(13)
    warning_form.mensaje.setFont(font)
    warning_form.mensaje.setAlignment(QtCore.Qt.AlignCenter)
    warning_form.mensaje.setObjectName(_fromUtf8("mensaje"))
    QtCore.QMetaObject.connectSlotsByName(warning_form)
    warning_form.setWindowTitle(QtGui.QApplication.translate("warning_form", "Form", None, QtGui.QApplication.UnicodeUTF8))
    warning_form.mensaje.setText(QtGui.QApplication.translate("warning_form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
